#ifndef SPATIAL_FILTER_PASS
#define SPATIAL_FILTER_PASS

#define UNFILTERED 1
#define GAUSSIAN   2
#define BOX        3

TEXTURE2D_X(_CloudColor);

// Matches the filter #define values. Set to UNFILTERED by default.
uniform int _ActiveSpatialFilter;

float4 gaussian_blur(float2 uv)
{
    // Replace this, was auto generated by AI
    float4 color = float4(0, 0, 0, 0);
    float weights[9] = {
        0.0625, 0.125, 0.0625,
        0.125,  0.25,  0.125,
        0.0625, 0.125, 0.0625
    };
    for (int i = -1; i <= 1; i++)
    {
        for (int j = -1; j <= 1; j++)
        {
            float2 offset = float2(i, j) / _ScreenParams.xy;
            color += SAMPLE_TEXTURE2D_X(_CloudColor, s_linear_clamp_sampler, uv + offset) * weights[(i + 1) * 3 + j + 1];
        }
    }
    return color;
}

float4 unfiltered(float2 uv)
{
    float4 color = SAMPLE_TEXTURE2D_X(_CloudColor, s_linear_clamp_sampler, uv);
    return color;
}

float4 SpatialPass(float2 uv)
{
    if (_ActiveSpatialFilter == GAUSSIAN)
    {
        return gaussian_blur(uv);
    }

    return unfiltered(uv);
}

#endif // SPATIAL_FILTER_PASS